name: deepseek-ocr
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.10

  # Deep Learning Framework
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - pytorch-cuda=12.1

  # System Dependencies
  - poppler  # For pdf2image

  # pip packages
  - pip
  - pip:
    # HuggingFace
    - transformers==4.47.1
    - hf_transfer>=0.1.9

    # DeepSeek-OCR Dependencies
    - addict>=2.4.0
    - einops>=0.8.0
    - easydict>=1.13

    # PDF Processing
    - PyMuPDF>=1.24.0
    - pdf2image>=1.17.0
    - Pillow>=10.0.0

    # Configuration
    - pyyaml>=6.0

    # Testing (Optional)
    - pytest>=8.4.0
    - pytest-asyncio>=0.23.0
